MANIFEST.in

Config directory has to be included in MANIFEST.in file.

Add config directory to MANIFEST.in

---

colin/core/config/config.py
colin/core/constant.py
setup.py

This Pull Request fixes issue #34 . CONFIG_DIRECTORY value missed `config` directory.

Fixes #34 add docu and update CONFIG_DIRECTORY

---

README.md
colin/cli/colin.py

* add --debug argument
* Related #33
* readme: provide usage from git
* Related #32
TODO:

UX improvements

---

colin/checks/abstract/abstract_check.py
colin/cli/colin.py
colin/core/colin.py

Add support for printing checks without running them.
- CLI option  `--print-checks`
- compatible with `--json` option
```
Usage: colin.py [OPTIONS] TARGET
Options:
-c, --config [redhat|fedora]  Select a predefined configuration.
-f, --config-file FILENAME    Path to a file to use for validation (by
default they are placed in /usr/share/colin).
--debug                       Enable debugging mode (debugging logs, full
tracebacks).
--json FILENAME               File to save the output as json to.
-s, --stat                    Print statistics instead of full results.
--print-checks                Print the checks without running them.
-v, --verbose                 Verbose mode.
-h, --help                    Show this message and exit.
```
```json
{
"labels": [
{
"name": …
```

Print checks

---

colin/checks/labels/distribution-scope.py
colin/checks/labels/release.py
colin/checks/labels/url.py
colin/checks/result.py
colin/cli/colin.py
colin/core/colin.py
colin/core/constant.py
colin/core/ruleset/ruleset.py

- Better output.
- Allow saving output to the string.
- Handle errors in the subcommands.
- Turn off the logs when no-debug.
- Print the statistics after the results.
- Allow filtering of the checks with the tags (e.g. `-t label -t maintainer`) (in `list-checks` and `check`)
----
- Correct super calls in some checks.
Resolves  #65

Implementation of the most useful output

---

colin/checks/labels.py
colin/cli/colin.py
colin/core/result.py
rulesets/fedora.json

- Better output when no check found.
- NoRootCheck not for dockerfiles.
- Correct name of the `io.k8s.display-name_label` check.
- Correct name of the `DistributionScopeLabelCheck`.

Small changes after big change

---

colin/checks/dockerfile.py
colin/checks/dynamic.py
colin/core/checks/abstract_check.py
colin/core/checks/cmd.py
colin/core/checks/dockerfile.py
rulesets/default.json

- Correct default ruleset file.
- Remove severity from the check str representation.
- Use AbstractCheck ending for all abstract checks.

Naming of abstract classes and another small changes after big change

---

release-conf.yaml

I don't see any wheels in https://pypi.org/project/colin/#files but `python3 setup.py bdist_wheel` and `python2 setup.py bdist_wheel` seem to make correct wheels so I hope you don't mind building/uploading wheels for python 2 and 3.

release-bot config file

---

colin/checks/best_practices.py
colin/core/check_runner.py
colin/core/checks/filesystem.py
tests/conftest.py
tests/data/Dockerfile-bash
tests/data/Dockerfile-ls
tests/integration/dynamic_check_data/Dockerfile-bash
tests/integration/test_dynamic_checks.py
tests/integration/test_fs_checks.py

* this saves so much time; also requires ton of memory if the image is
beefy
\+
* error messages: grammar
* move test images creation to conftest.py

do not mount whole FS when checking for files

---

colin/checks/labels.py

- Correct the 'labels' attribute of the check.

Correct the io.k8s.display-name check

---

colin/checks/labels.py

- Correct description for the 'description_or_io.k8s.description_label' check.

Correct description for the description checks

---

colin/core/checks/fmf_check.py
colin/core/fmf_extension.py

- it use just expected parameter for class invocation, avoid to ``del`` expected attribute. Will be useful in case of `rulesets` too
- prepare for more checks directories with one ruleset.

get just parameters from metadata what has to be used for class invocation

---

README.md

It's grey at the moment since there have not been any build in [the job](https://ci.centos.org/job/user-cont-colin-master/) yet.

[README.md] Add build status badge

---

tests/unit/test_cli.py

Fix [errors in Centos CI](https://ci.centos.org/job/user-cont-colin-pr/51/console):
```
13:41:12 ______________________________ test_check_command ______________________________
13:41:12 
13:41:12     def test_check_command():
13:41:12         result = _call_colin(check)
13:41:12         expected_output = """Usage: check [OPTIONS] TARGET
13:41:12    
13:41:12     Error: Missing argument "target".
13:41:12     """ 
13:41:12         assert result.exit_code == 2
13:41:12 >       assert result.output == expected_output
13:41:12 E       assert 'Usage: check...t "TARGET".\n' == 'Usage: check ...t "target".\n'
13:41:12 E           Usage: check [OPTIONS] TARGET
13:41:12 E         - Try "check -h" for help.
13:41:12 E    
13:41:12 E         - Error: Missing argument "TARGET".
13:41:12 E         ? …
```

Correct CLI test

---

CHANGELOG.md

@user-cont/the-team when you are writing changelogs for our open source projects, please think about these:
* The changelog is meant to be read by everyone. Imagine that an average user
will read it and should understand the changes. `Add check timeouts` is
completely undescriptive.
* Every line should be a complete sentence. Either tell what is the change that the tool is doing or describe it precisely:
* Bad: `Use search method in label regex`
* Good: `Colin now uses search method when...`
* And finally, with the changelogs we are essentially selling our projects:
think about a situation that you met someone at a conference and you are
trying to convince the person to use the project and that the changelog
should help with that.

more descriptive 0.3.0 changelog

---

colin.spec
colin/checks/best_practices.py
colin/cli/colin.py
colin/core/checks/cmd.py
colin/core/checks/filesystem.py
colin/core/colin.py
docs/python_api.rst
release-conf.yaml
setup.py
tests/unit/test_cli.py

- Remove Python2 from setup.py.
- Is there anything else that needs to be done in specfile?
- Allow metadata checks for podman images.
- Remove conu for now.
- We can add it later with move to the conu-podman backend.

Packaging and metadata fixes

---

Dockerfile.tests
colin/core/check_runner.py
tests/unit/test_cli.py

```
timeout = timeout or check.timeout or CHECK_TIMEOUT
```
Timeout for checks was based on 3 different values.
a) argument `timeout` which was passed from command line --timeout
b) timeout specified in check in result_set
c) predefined default value `CHECK_TIMEOUT`
The bug was that value of argument was changed in the function
and there is nothing like pass by value in python.
Right timeout was used for the 1st check but not for others.
@lachmanfrantisek @TomasTomecek PTAL

check_runner: Allow to overwrite timeout in result_set

---

colin/cli/colin.py
colin/core/result.py
tests/unit/test_cli.py

Adds a function so that the test results are outputted as an xunit xml file that can be parsed by things that support it.

Add function to convert results to an xunit xml file

---

CONTRIBUTING.md

Currently, the directions in `CONTRIBUTING.md` tell users to point the
`--checks-path` CLI option to an external file,
`/tmp/external_checks/checks.py`. This is inconsistent with the current
`--checks-path` functionality and CLI help menu description which states
that the `--checks-path` option should point to a "directory containing
checks."
This fix to `CONTRIBUTING.md` is intended to clear up any confusion for
new users of the project.
Signed-off-by: Rose Judge <rjudge@vmware.com>

Fix CONTRIBUTING.md to reflect correct CLI args

---

Dockerfile.tests
colin/cli/colin.py
colin/core/colin.py
colin/core/target.py
tests/conftest.py
tests/integration/test_targets.py
tests/unit/test_cli.py

The support for ostree was removed from skopeo in fedora 31 and from podman in fedora 30.

Add OCI support for unprivileged checks

---

colin/checks/best_practices.py
colin/cli/colin.py
colin/core/check_runner.py
colin/core/checks/abstract_check.py
colin/core/checks/check_utils.py
colin/core/checks/cmd.py
colin/core/checks/filesystem.py
colin/core/checks/fmf_check.py
colin/core/checks/labels.py
colin/core/fmf_extension.py
colin/core/loader.py
colin/core/result.py
colin/core/ruleset/loader.py
colin/core/ruleset/ruleset.py
colin/core/target.py
colin/utils/cmd_tools.py
colin/utils/cont.py
tests/conftest.py
tests/unit/test_loader.py

* Use flynt to convert old forms of string templating.
* Use `%s` in logger and forward arguments.

Use fstrings and avoid templating in logger

---

.pre-commit-config.yaml

I've added a rebase check to pre-commit
1. in case you have already installed pre-commit hooks: `pre-commit install -t pre-push`, to install pre-push
2. in case you run pre-commit manually, add `--hook-stage manual` switch
It's set for manual and push, since pre-commit CI runs without network, thus can't check it there. Better than nothing ;)
Signed-off-by: Matej Focko <mfocko@redhat.com>

Add rebase check to pre-commit as pre-push hook

---

CHANGELOG.md
colin.spec
colin/version.py

We need to update version in the following places:
* `./colin/version.py`
* `./colin.spec` (`Version` tag and a new changelog entry)
* new changelog entry in `./CHANGELOG.md`
Sorry for the mess with the previous release. I forgot to update `./colin/version.py` and the PyPI release failed because of that:
https://github.com/user-cont/colin/runs/4786572941?check_suite_focus=true

Create a new `0.5.2` release that replaces the badly done `0.5.1`

---

docs/list_of_checks.rst

Now that #285 has fixed the hardcoding of `/usr/local/` in the code, this PR fixes it in the documentation. The fixed path is replaced with a hyperlinked `sys.prefix`, leading to the relevant section of the Python docs. I also corrected the user default path (`~/.local/...`, not `~/local/...`.)
While I was in there I noticed that the strings intended to be inline literals (I presume) weren't showing that way, because they were written using MarkDown syntax (\`single backtick\` fencing) rather than RST syntax (\`\`double backtick\`\` fencing), so I fixed those as well.

docs/list_of_checks: Formatting, ref sys.prefix

---

colin/core/ruleset/ruleset.py
docs/list_of_checks.rst

Running list-rulesets will fail for package installed from PyPI
```
[root@b04c448e74fc /]# dnf install -y -e0 -d0 podman python3-pip
//snip
[root@b04c448e74fc /]# pip install colin==0.5.2
//snip
[root@b04c448e74fc /]# python3 -c 'import colin; print(colin.__path__)'
['/usr/local/lib/python3.9/site-packages/colin']
[root@b04c448e74fc /]# ls -l /usr/local/share/colin/rulesets/
total 8
-rw-r--r--. 1 root root  582 Mar  1 16:52 default.json
-rw-r--r--. 1 root root 1611 Mar  1 16:52 fedora.json
[root@b04c448e74fc /]# /usr/local/bin/colin list-rulesets
Ruleset directory cannot be found.
An error occurred: ColinRulesetException('Ruleset directory cannot be found.')
Error: Ruleset directory cannot be found.
```
There does not seems to be any trivial and reliable way how to identify
where …

Add workaround for default instalation from PyPI
