colin/checks/labels/name.py

This pull request brings support for label NAME which has to exists in each container.

Name label check

---

colin/checks/labels/com_redhat_component.py
colin/core/config/fedora.json
colin/core/config/rhel.json

This Pull Request brings support for com.redhat.com label

Add support for com.redhat.component label

---

colin/__init__.py
colin/checks/abstract/abstract_check.py
colin/checks/abstract/dockerfile.py
colin/checks/abstract/labels.py
colin/checks/dockerfile/layered_run.py
colin/checks/labels/com_redhat_component.py
colin/checks/labels/maintainer.py
colin/checks/labels/name.py
colin/checks/result.py
colin/core/check_runner.py
colin/core/colin.py
colin/core/config/config.py
colin/core/constant.py
colin/core/loader.py
colin/core/target.py

[WIP] Add basic validation pipeline

---

colin/checks/abstract/containers.py
colin/checks/abstract/dockerfile.py
colin/checks/abstract/images.py
colin/checks/abstract/labels.py
colin/core/check_runner.py
colin/core/colin.py
colin/core/config/config.py
colin/core/loader.py
colin/core/target.py

Make the internal imports relative

---

MANIFEST.in
setup.py

This PR adds MANIFEST.in and fix setup.py, which is not human readable, by my option

Fix packaging stuff.

---

colin/cli/colin.py
colin/core/config/config.py
colin/core/exceptions.py
colin/core/target.py

Add better error catching

---

README.md

Add installation instruction to the README

---

colin/checks/labels/io_k8s_dipslay-name.py
colin/checks/labels/io_openshift_tags.py
config/rhel.json

This Pull Request adds to check labels. One for `io.k8s.display-name` and second one for `io.openshift.tags`.

Required OpenShift labels.

---

colin/checks/abstract/abstract_check.py
colin/checks/abstract/labels.py
colin/checks/result.py
colin/cli/colin.py
colin/core/check_runner.py
colin/core/config/config.py
colin/core/constant.py
colin/core/loader.py

Provides:
- streaming of results
- saving result to json with `--json` option
Resolves #14

Better and streamed output

---

colin/checks/labels/architecture.py
colin/checks/labels/authoritative-source-url.py
colin/checks/labels/build-date.py
colin/checks/labels/com_redhat_build-host.py
colin/checks/labels/com_redhat_component.py
colin/checks/labels/description.py
colin/checks/labels/distribution-scope.py
colin/checks/labels/help.py
colin/checks/labels/io_k8s_description.py
colin/checks/labels/release.py
colin/checks/labels/url.py
colin/checks/labels/vcs-ref.py
colin/checks/labels/vcs-type.py
colin/checks/labels/vendor.py
config/fedora.json
config/rhel.json

Add RHEL required labels

---

colin/cli/colin.py
colin/core/colin.py
colin/core/config/config.py

Allow loading config from file

---

README.md

Add usage of the container checking to README

---

LICENSE
README.md
colin/checks/abstract/abstract_check.py
colin/checks/abstract/containers.py
colin/checks/abstract/dockerfile.py
colin/checks/abstract/filesystem.py
colin/checks/abstract/images.py
colin/checks/abstract/labels.py
colin/checks/result.py
colin/cli/colin.py
colin/core/check_runner.py
colin/core/colin.py
colin/core/config/config.py
colin/core/constant.py
colin/core/exceptions.py
colin/core/loader.py
colin/core/target.py
setup.py

Add license

---

setup.py

Is there anything else, that needs to be added here?

Better setup py

---

colin/checks/abstract/labels.py
colin/checks/labels/architecture_capital_deprecated.py
colin/checks/labels/bzcomponent_deprecated.py
colin/checks/labels/install_capital_deprecated.py
colin/checks/labels/name_capital_deprecated.py
colin/checks/labels/release_capital_deprecated.py
colin/checks/labels/uninstall_capital_deprecated.py
colin/checks/labels/version_capital_deprecated.py
config/redhat.json

Add checks for deprecated labels.
(If there is a deprecated version, there needs to be also the new version.)

Deprecated labels

---

README.md
setup.py

Changes after release to PyPI

---

setup.py

Prepare release v0.0.2

---

setup.cfg

Add config for PyPI to see description on the PyPI web

---

setup.py

This Pull Request modifies setup.py according Click guidelines http://click.pocoo.org/5/setuptools/#scripts-in-packages.

Use entrypoint according Click docu

---

colin/cli/colin.py

Otherwise, the CLI is broken...

Correct CLI function

---

colin/cli/colin.py
colin/core/colin.py
colin/core/target.py
tests/test_image_name.py

Resolves #11 
- Added also support for instance of conu Image/Container class in target (needs some parameter renames)
- Image id is not supported now. (Need some work on the conu side.)

Better name parsing

---

colin/version.py

Prepare release v0.0.3

---

setup.cfg
setup.py

Correct the description for PyPI

---

colin/cli/colin.py
colin/cli/default_group.py
colin/core/colin.py
colin/core/target.py

Final cli design

---

colin/checks/abstract/envs.py

Add abstract check for environment variables

Add abstract check for the environemnt variable

---

colin/checks/abstract/envs.py

Correct check for env variables

Correct env_var check

---

colin/checks/result.py
colin/cli/colin.py
colin/core/check_runner.py
colin/core/colin.py
colin/core/constant.py

Print logs only for --debug
Return better return codes
Provide error handling for checks

Error handling, better output, return codes

---

.travis.yml
MANIFEST.in
Makefile
colin.spec
setup.py

This issue adds colin.spec file and some packaging fixes.
I tested it in real installation process and usage process. (COPR https://copr.fedorainfracloud.org/coprs/phracek/colin/)

Fixes #64 colin.spec and packaging fixes

---

Makefile
README.md
local.yml

This Pull Request brings the new option for colin local testing by `ansible` playbook.
Please look at it and review.

Add info about local testing

---

CONTRIBUTING.md

This Pull Request adds CONTRIBUTING.md file and especially part, how to add the new check.
Please look and review it.
It partially fixes #71 .

Add CONTRIBUTING.md file, especially how to add new checks

---

README.md
colin/cli/colin.py

Split exit codes and mention them in the README

Better exit codes

---

colin/version.py

Prepare release v0.0.4

---

colin.spec

Change version also in the spec file
Please wait a bit. Not merge now!

Change version also in the spec file

---

colin.spec
tests/data/Dockerfile

- Add changelog to specfile
- Increase version in Dockerfile

Add changelog to specfile

---

colin.spec

This Pull Request updates the colin.spec file.
Don't close it yet till BZ https://bugzilla.redhat.com/show_bug.cgi?id=1572084 is not approved.

Fixes #105: Fix issues catched by BZ review request

---

.gitignore
colin/__init__.py
colin/core/colin.py
colin/core/constant.py
colin/core/ruleset/ruleset.py
tests/integration/test_ruleset_file.py
tests/unit/test_cli.py

enable passing ruleset dict to colin.run() and .get_checks

---

colin.spec

Next one PR for packaging issues.

WIP: Remove autogenerated files by sphinx WIP

---

colin.spec

Remove dot from summary

---

colin/checks/result.py
colin/core/check_runner.py
colin/utils/caching_iterable.py
tests/integration/test_labels.py

- Use caching iterable for results.
- Add caching iterable class.

Better results iterable

---

colin/checks/abstract/cmd.py
colin/checks/dynamic/shell.py
colin/checks/result.py
colin/core/check_runner.py
colin/core/target.py
tests/integration/dynamic_check_data/Dockerfile-bash
tests/integration/dynamic_check_data/Dockerfile-ls
tests/integration/test_dynamic_checks.py

- Add first dynamic check
- Add logging of the output for the dynamic checks
- Add abstract check for dynamic checks
-----
Any ideas for new dynamic checks?

Dynamic checks

---

tests/unit/test_cli.py

Correct test output for list-checks

Correct test for list-checks

---

.bandit
.landscape.yaml
.pylintrc
README.md

- Move badges behind the title.
- Add code-ci config files.

Support for code-style CI

---

Makefile
colin/cli/colin.py
colin/core/loader.py
colin/core/result.py
colin/core/ruleset/loader.py

- Resolve some codacy warnings.
- Add pylint and bandit to Makefile.

Resolve some codacy warnings

---

colin/core/ruleset/loader.py
rulesets/fedora.json
tests/integration/test_ruleset_file.py

- Use checks grouping in fedora rulese.
- Add support for grouping checks in ruleset.
-----

Grouping checks in rulesets

---

colin/checks/best_practices.py
colin/core/checks/envs.py
colin/core/target.py

adapt to conu 0.4.0

---

.bandit

- Use bandit file from kwaciaren.
-----
Please, do not change .bandit/.pylintrc files here, but first in [our config repo](https://github.com/user-cont/kwaciaren) so we can share common configuration between all projects.
(Kwaciaren, the config repo, has scripts for sharing such files.)

Use config from user-cont/kwaciaren

---

README.md
colin/checks/labels.py
docs/index.rst
docs/list_of_checks.rst
rulesets/fedora.json
tests/integration/test_labels.py

remove io.openshift.* labels checks

---

CONTRIBUTING.md
colin/cli/colin.py
colin/core/colin.py
colin/core/loader.py
colin/core/ruleset/ruleset.py
tests/data/a_check/__init__.py
tests/data/a_check/another_checks.py
tests/unit/test_loader.py

Fixes #127 
* contrib.md: fix examples, doc external checks
* --checks-path now accepts a list of paths

external checks:

---

colin/cli/colin.py

- Check existence of json outpuit file directory.
Resolves #139

Check directory for json output

---

tests/unit/test_loader.py

- Fix openshift labels in tests.

Fix openshift labels in tests

---

colin/cli/colin.py
colin/core/ruleset/ruleset.py

Rulesets discovery from all expected directories

---

release-conf.yaml

see https://github.com/user-cont/release-bot/pull/76

Allow release-bot to make PRs based on issues

---

colin/checks/best_practices.py
colin/core/result.py
rulesets/fedora.json
tests/data/Dockerfile
tests/integration/test_labels.py
tests/integration/test_targets.py

There was a bug internally and I just want to make it clear we test for the scenario which resulted into a failure.

test properly usable_targets with different target types

---

setup-ci.sh

Fix xattr in CI

---

colin/cli/colin.py
colin/utils/cmd_tools.py
tests/unit/test_cli.py

- Add info subcommand.
resolves #183

Add info subcommand

---

colin/core/ruleset/ruleset.py

- Allow loading rulesets from virtualenv.

Rulesets in virtualenv

---

colin/cli/colin.py
tests/unit/test_cli.py

- Allow to set cli option from the environment variable.

Set CLI option from the environment variable

---

colin/checks/dockerfile.py
tests/integration/test_dockerfile.py

- Error check-result when missing FROM in testing image tag.
Fix #162

Fix missing FROM in tag_not_latest

---

colin/checks/best_practices.py
colin/checks/dockerfile.py
colin/core/checks/abstract_check.py
colin/core/checks/check_utils.py
colin/core/checks/cmd.py
colin/core/checks/dockerfile.py
colin/core/checks/envs.py
colin/core/checks/filesystem.py
colin/core/checks/images.py
colin/core/checks/labels.py
colin/core/ruleset/ruleset.py
colin/core/target.py
tests/integration/test_ruleset_file.py

- Use NotLoadedCheck when the code cannot be found.
- Test for NotLoadedCheck.

Loading checks without code

---

colin/core/checks/check_utils.py
colin/core/checks/labels.py

Use search method in label regex.

---

colin/cli/colin.py
colin/core/colin.py
colin/core/ruleset/ruleset.py
tests/integration/test_ruleset_file.py
tests/unit/test_cli.py

Check skip support

---

colin/utils/cmd_tools.py
tests/unit/test_utils.py

It might be useful in checks which do lot of network communication.
@TomasTomecek  @lachmanfrantisek PTAL

Utils: Add decorator for retry in case of raised exception

---

release-conf.yaml

https://lists.fedoraproject.org/archives/list/devel-announce@lists.fedoraproject.org/message/VNCIQRESRZX3Q74WL5TLZCQW7LHLTGQM/

[release-conf.yaml] F30 has been branched

---

.packit.yaml

So that it's not confusing to people.

Make packit.yaml minimal

---

.packit.yaml

Use packit aliases

---

colin/core/result.py
tests/integration/test_labels.py

* Remove unused argument 'fg'
* Drop unused test test_colin_image
It is already covered by the test test_labels_in_image
(and parameter None)

Remove unused code

---

.github/workflows/pypi-publish.yml

Token has been added to the project secrets.

Add workflow for uploading release to PyPI

---

CHANGELOG.md
colin.spec
colin/version.py

Prepare release 0.5.0

---

ci.fmf
colin/core/ruleset/ruleset.py

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2036710
Fixes: #260

Make the location of ruleset more generic

---

colin/core/checks/abstract_check.py
colin/core/checks/check_utils.py
colin/core/checks/fmf_check.py
colin/core/colin.py
colin/core/loader.py
colin/core/result.py
colin/core/ruleset/ruleset.py
colin/core/target.py
colin/utils/cmd_tools.py
tests/conftest.py
tests/integration/test_labels.py
tests/integration/test_ruleset_file.py
tests/unit/test_ruleset.py

I've used [Sourcery](https://sourcery.ai/) PyCharm plugin to improve some parts of the code a bit.

Sourcery suggestions

---

.packit.yaml

Run Koji builds automatically for new dist-git commits
